{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "callisto.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "callisto.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "callisto.name" . }}
  namespace: {{ .Release.Namespace }}
{{ end }}
