apiVersion: v1
kind: Service
metadata:
  name: {{ template "callisto.name" . }}
  labels:
    app: {{ template "callisto.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.callisto.service.type }}
  {{- if not .Values.callisto.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.callisto.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: callisto
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ template "callisto.name" . }}
    release: {{ .Release.Name }}
