apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "callisto.name" . }}-selenoid-ui
  labels:
    app: {{ template "callisto.name" . }}-selenoid-ui
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.selenoidUi.replicas }}
  minReadySeconds: {{ .Values.selenoidUi.minReadySeconds }}
  selector:
    matchLabels:
      app: {{ template "callisto.name" . }}-selenoid-ui
  strategy:
  {{- if .Values.selenoidUi.strategy }}
  {{ toYaml .Values.selenoidUi.strategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "callisto.name" . }}-selenoid-ui
        release: "{{ .Release.Name }}"
        instance_id: {{ .Values.instanceID | quote }}
        {{- if .Values.callisto.podLabels }}
        {{ toYaml.Values.callisto.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.callisto.podAnnotations  }}
        {{ toYaml.Values.callisto.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - image: {{ template "selenoidUi.image" . }}
        name: selenoid-ui
        imagePullPolicy: {{ .Values.selenoidUi.image.pullPolicy }}
        args: ["-selenoid-uri", "http://{{ template "callisto.name" . }}-nginx/callisto", "-listen", ":8000"]
        resources:
        {{ toYaml .Values.selenoidUi.resources | nindent 10 }}
        ports:
          - name: selenoid-ui
            containerPort: 8000
      affinity:
      {{- if .Values.selenoidUi.affinity }}
      {{ toYaml .Values.selenoidUi.affinity | nindent 8 }}
      {{- end }}
      tolerations:
      {{- if .Values.selenoidUi.tolerations }}
      {{ toYaml .Values.selenoidUi.tolerations | nindent 8 }}
      {{- end }}
      volumes:
      {{- with .Values.selenoidUi.volumes }}
      {{ toYaml .Values.selenoidUi.volumes | indent 8 }}
      {{- end }}
